<?php

return [
    'banks' => [
        [
            "name" => "9mobile 9Payment Service Bank",
            "slug" => "9mobile-9payment-service-bank-ng",
            "code" => "120001",
            "long_code" => "120001",
            "gateway" => "",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Abbey Mortgage Bank",
            "slug" => "abbey-mortgage-bank",
            "code" => "801",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Above Only MFB",
            "slug" => "above-only-mfb",
            "code" => "51204",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Abulesoro MFB",
            "slug" => "abulesoro-mfb-ng",
            "code" => "51312",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Access Bank",
            "slug" => "access-bank",
            "code" => "044",
            "long_code" => "044150149",
            "gateway" => "emandate",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*901#",
            "logo" => "https://nigerianbanks.xyz/logo/access-bank.png"
        ],
        [
            "name" => "Access Bank (Diamond)",
            "slug" => "access-bank-diamond",
            "code" => "063",
            "long_code" => "063150162",
            "gateway" => "emandate",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*426#",
            "logo" => "https://nigerianbanks.xyz/logo/access-bank-diamond.png"
        ],
        [
            "name" => "Airtel Smartcash PSB",
            "slug" => "airtel-smartcash-psb-ng",
            "code" => "120004",
            "long_code" => "120004",
            "gateway" => "",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "ALAT by WEMA",
            "slug" => "alat-by-wema",
            "code" => "035A",
            "long_code" => "035150103",
            "gateway" => "emandate",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*945*100#",
            "logo" => "https://nigerianbanks.xyz/logo/alat-by-wema.png"
        ],
        [
            "name" => "Amju Unique MFB",
            "slug" => "amju-unique-mfb",
            "code" => "50926",
            "long_code" => "511080896",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Aramoko MFB",
            "slug" => "aramoko-mfb",
            "code" => "50083",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "ASO Savings and Loans",
            "slug" => "asosavings",
            "code" => "401",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/asosavings.png"
        ],
        [
            "name" => "Astrapolaris MFB LTD",
            "slug" => "astrapolaris-mfb",
            "code" => "MFB50094",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Bainescredit MFB",
            "slug" => "bainescredit-mfb",
            "code" => "51229",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Bowen Microfinance Bank",
            "slug" => "bowen-microfinance-bank",
            "code" => "50931",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Carbon",
            "slug" => "carbon",
            "code" => "565",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "CEMCS Microfinance Bank",
            "slug" => "cemcs-microfinance-bank",
            "code" => "50823",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/cemcs-microfinance-bank.png"
        ],
        [
            "name" => "Chanelle Microfinance Bank Limited",
            "slug" => "chanelle-microfinance-bank-limited-ng",
            "code" => "50171",
            "long_code" => "50171",
            "gateway" => "",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Citibank Nigeria",
            "slug" => "citibank-nigeria",
            "code" => "023",
            "long_code" => "023150005",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/citibank-nigeria.png"
        ],
        [
            "name" => "Corestep MFB",
            "slug" => "corestep-mfb",
            "code" => "50204",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Coronation Merchant Bank",
            "slug" => "coronation-merchant-bank",
            "code" => "559",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Crescent MFB",
            "slug" => "crescent-mfb",
            "code" => "51297",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Ecobank Nigeria",
            "slug" => "ecobank-nigeria",
            "code" => "050",
            "long_code" => "050150010",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*326#",
            "logo" => "https://nigerianbanks.xyz/logo/ecobank-nigeria.png"
        ],
        [
            "name" => "Ekimogun MFB",
            "slug" => "ekimogun-mfb-ng",
            "code" => "50263",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Ekondo Microfinance Bank",
            "slug" => "ekondo-microfinance-bank",
            "code" => "562",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*540*178#",
            "logo" => "https://nigerianbanks.xyz/logo/ekondo-microfinance-bank.png"
        ],
        [
            "name" => "Eyowo",
            "slug" => "eyowo",
            "code" => "50126",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Fidelity Bank",
            "slug" => "fidelity-bank",
            "code" => "070",
            "long_code" => "070150003",
            "gateway" => "emandate",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*770#",
            "logo" => "https://nigerianbanks.xyz/logo/fidelity-bank.png"
        ],
        [
            "name" => "Firmus MFB",
            "slug" => "firmus-mfb",
            "code" => "51314",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "First Bank of Nigeria",
            "slug" => "first-bank-of-nigeria",
            "code" => "011",
            "long_code" => "011151003",
            "gateway" => "ibank",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*894#",
            "logo" => "https://nigerianbanks.xyz/logo/first-bank-of-nigeria.png"
        ],
        [
            "name" => "First City Monument Bank",
            "slug" => "first-city-monument-bank",
            "code" => "214",
            "long_code" => "214150018",
            "gateway" => "emandate",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*329#",
            "logo" => "https://nigerianbanks.xyz/logo/first-city-monument-bank.png"
        ],
        [
            "name" => "FSDH Merchant Bank Limited",
            "slug" => "fsdh-merchant-bank-limited",
            "code" => "501",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Gateway Mortgage Bank LTD",
            "slug" => "gateway-mortgage-bank",
            "code" => "812",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Globus Bank",
            "slug" => "globus-bank",
            "code" => "00103",
            "long_code" => "103015001",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*989#",
            "logo" => "https://nigerianbanks.xyz/logo/globus-bank.png"
        ],
        [
            "name" => "GoMoney",
            "slug" => "gomoney",
            "code" => "100022",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Guaranty Trust Bank",
            "slug" => "guaranty-trust-bank",
            "code" => "058",
            "long_code" => "058152036",
            "gateway" => "ibank",
            "pay_with_bank" => true,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*737#",
            "logo" => "https://nigerianbanks.xyz/logo/guaranty-trust-bank.png"
        ],
        [
            "name" => "Hackman Microfinance Bank",
            "slug" => "hackman-microfinance-bank",
            "code" => "51251",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Hasal Microfinance Bank",
            "slug" => "hasal-microfinance-bank",
            "code" => "50383",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*322*127#",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Heritage Bank",
            "slug" => "heritage-bank",
            "code" => "030",
            "long_code" => "030159992",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*322#",
            "logo" => "https://nigerianbanks.xyz/logo/heritage-bank.png"
        ],
        [
            "name" => "HopePSB",
            "slug" => "hopepsb-ng",
            "code" => "120002",
            "long_code" => "120002",
            "gateway" => "",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Ibile Microfinance Bank",
            "slug" => "ibile-mfb",
            "code" => "51244",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Ikoyi Osun MFB",
            "slug" => "ikoyi-osun-mfb",
            "code" => "50439",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Infinity MFB",
            "slug" => "infinity-mfb",
            "code" => "50457",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Jaiz Bank",
            "slug" => "jaiz-bank",
            "code" => "301",
            "long_code" => "301080020",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*389*301#",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Kadpoly MFB",
            "slug" => "kadpoly-mfb",
            "code" => "50502",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Keystone Bank",
            "slug" => "keystone-bank",
            "code" => "082",
            "long_code" => "082150017",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*7111#",
            "logo" => "https://nigerianbanks.xyz/logo/keystone-bank.png"
        ],
        [
            "name" => "Kredi Money MFB LTD",
            "slug" => "kredi-money-mfb",
            "code" => "50200",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Kuda Bank",
            "slug" => "kuda-bank",
            "code" => "50211",
            "long_code" => "",
            "gateway" => "digitalbankmandate",
            "pay_with_bank" => true,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/kuda-bank.png"
        ],
        [
            "name" => "Lagos Building Investment Company Plc.",
            "slug" => "lbic-plc",
            "code" => "90052",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Links MFB",
            "slug" => "links-mfb",
            "code" => "50549",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Living Trust Mortgage Bank",
            "slug" => "living-trust-mortgage-bank",
            "code" => "031",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Lotus Bank",
            "slug" => "lotus-bank",
            "code" => "303",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Mayfair MFB",
            "slug" => "mayfair-mfb",
            "code" => "50563",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Mint MFB",
            "slug" => "mint-mfb",
            "code" => "50304",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "MTN Momo PSB",
            "slug" => "mtn-momo-psb-ng",
            "code" => "120003",
            "long_code" => "120003",
            "gateway" => "",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "One Finance",
            "slug" => "one-finance",
            "code" => "565",
            "long_code" => "",
            "gateway" => "",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*1303#",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Paga",
            "slug" => "paga",
            "code" => "100002",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/paga.png"
        ],
        [
            "name" => "PalmPay",
            "slug" => "palmpay",
            "code" => "999991",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Parallex Bank",
            "slug" => "parallex-bank",
            "code" => "104",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*322*318*0#",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Parkway - ReadyCash",
            "slug" => "parkway-ready-cash",
            "code" => "311",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Paycom",
            "slug" => "paycom",
            "code" => "999992",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*955#",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Petra Mircofinance Bank Plc",
            "slug" => "petra-microfinance-bank-plc",
            "code" => "50746",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Polaris Bank",
            "slug" => "polaris-bank",
            "code" => "076",
            "long_code" => "076151006",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*833#",
            "logo" => "https://nigerianbanks.xyz/logo/polaris-bank.png"
        ],
        [
            "name" => "Polyunwana MFB",
            "slug" => "polyunwana-mfb-ng",
            "code" => "50864",
            "long_code" => "null",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "PremiumTrust Bank",
            "slug" => "premiumtrust-bank-ng",
            "code" => "105",
            "long_code" => "000031",
            "gateway" => "",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Providus Bank",
            "slug" => "providus-bank",
            "code" => "101",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "QuickFund MFB",
            "slug" => "quickfund-mfb",
            "code" => "51293",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Rand Merchant Bank",
            "slug" => "rand-merchant-bank",
            "code" => "502",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Refuge Mortgage Bank",
            "slug" => "refuge-mortgage-bank",
            "code" => "90067",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Rubies MFB",
            "slug" => "rubies-mfb",
            "code" => "125",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*7797#",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Safe Haven MFB",
            "slug" => "safe-haven-mfb-ng",
            "code" => "51113",
            "long_code" => "51113",
            "gateway" => "",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Solid Rock MFB",
            "slug" => "solid-rock-mfb",
            "code" => "50800",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Sparkle Microfinance Bank",
            "slug" => "sparkle-microfinance-bank",
            "code" => "51310",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/sparkle-microfinance-bank.png"
        ],
        [
            "name" => "Stanbic IBTC Bank",
            "slug" => "stanbic-ibtc-bank",
            "code" => "221",
            "long_code" => "221159522",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*909#",
            "logo" => "https://nigerianbanks.xyz/logo/stanbic-ibtc-bank.png"
        ],
        [
            "name" => "Standard Chartered Bank",
            "slug" => "standard-chartered-bank",
            "code" => "068",
            "long_code" => "068150015",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/standard-chartered-bank.png"
        ],
        [
            "name" => "Stellas MFB",
            "slug" => "stellas-mfb",
            "code" => "51253",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Sterling Bank",
            "slug" => "sterling-bank",
            "code" => "232",
            "long_code" => "232150016",
            "gateway" => "emandate",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*822#",
            "logo" => "https://nigerianbanks.xyz/logo/sterling-bank.png"
        ],
        [
            "name" => "Suntrust Bank",
            "slug" => "suntrust-bank",
            "code" => "100",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*5230#",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "TAJ Bank",
            "slug" => "taj-bank",
            "code" => "302",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*898#",
            "logo" => "https://nigerianbanks.xyz/logo/taj-bank.png"
        ],
        [
            "name" => "Tangerine Money",
            "slug" => "tangerine-money",
            "code" => "51269",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "TCF MFB",
            "slug" => "tcf-mfb",
            "code" => "51211",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*908#",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Titan Bank",
            "slug" => "titan-bank",
            "code" => "102",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*922#",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Titan Paystack",
            "slug" => "titan-paystack-ng",
            "code" => "100039",
            "long_code" => "",
            "gateway" => "",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Unical MFB",
            "slug" => "unical-mfb",
            "code" => "50871",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Union Bank of Nigeria",
            "slug" => "union-bank-of-nigeria",
            "code" => "032",
            "long_code" => "032080474",
            "gateway" => "emandate",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*826#",
            "logo" => "https://nigerianbanks.xyz/logo/union-bank-of-nigeria.png"
        ],
        [
            "name" => "United Bank For Africa",
            "slug" => "united-bank-for-africa",
            "code" => "033",
            "long_code" => "033153513",
            "gateway" => "emandate",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*919#",
            "logo" => "https://nigerianbanks.xyz/logo/united-bank-for-africa.png"
        ],
        [
            "name" => "Unity Bank",
            "slug" => "unity-bank",
            "code" => "215",
            "long_code" => "215154097",
            "gateway" => "emandate",
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*7799#",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "VFD Microfinance Bank Limited",
            "slug" => "vfd",
            "code" => "566",
            "long_code" => "",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "",
            "logo" => "https://nigerianbanks.xyz/logo/default-image.png"
        ],
        [
            "name" => "Wema Bank",
            "slug" => "wema-bank",
            "code" => "035",
            "long_code" => "035150103",
            "gateway" => null,
            "pay_with_bank" => false,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*945#",
            "logo" => "https://nigerianbanks.xyz/logo/wema-bank.png"
        ],
        [
            "name" => "Zenith Bank",
            "slug" => "zenith-bank",
            "code" => "057",
            "long_code" => "057150013",
            "gateway" => "emandate",
            "pay_with_bank" => true,
            "is_active" => true,
            "country_id" => 160,
            "currency_id" => 160,
            "type" => "nuban",
            "ussd" => "*966#",
            "logo" => "https://nigerianbanks.xyz/logo/zenith-bank.png"
        ]
    ]
];
